---
- hosts: dev
  become: yes

  vars_files:
    - vars.yml

  vars:
    tag: "{{ lookup('env', 'TAG') }}"
    acr_password: "{{ lookup('env', 'ACR_PASSWORD') }}"

  roles:
    - role: ../roles/acr
      # tags: [login]
    - role: ../roles/deploy
      # tags: [deploy]
