name: CD
run-name: CD ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches:
      - main

env:
  REGION_ID: cn-shanghai
  REGISTRY: crpi-notabmu0yl0rr8sv.cn-shanghai.personal.cr.aliyuncs.com
  NAMESPACE: s1line1-test
  IMAGE: github-actions-demo

jobs:
  unit_test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build test image
        run: |
          docker build \
            -f Dockerfile.test \
            -t springboot-test:${{ github.sha }} \
            .

      - name: Run mvn clean verify
        run: |
          docker run --rm \
            springboot-test:${{ github.sha }} \
            bash cicd/run-test.sh

  # check_image_tag:
  #   name: Get Latest Image Tag
  #   runs-on: ubuntu-latest
  #   outputs:
  #     image_tag: ${{ steps.get-tag.outputs.tag }}
  #   steps:
  #     - name: Login to ACR
  #       id: login-acr
  #       run: |
  #         echo "${{ secrets.ACR_PASSWORD }}" | docker login \
  #           -u 个人云数据 \
  #           --password-stdin \
  #           "${{ env.REGISTRY }}"

  #     - name: Get latest tag from ACR
  #       id: get-tag
  #       env:
  #         REGISTRY: ${{ env.REGISTRY }}
  #         NAMESPACE: ${{ env.NAMESPACE }}
  #         IMAGE: ${{ env.IMAGE }}
  #       run: |
  #         set -euo pipefail

  #         AUTH_HEADER=$(curl -sI "https://$REGISTRY/v2/" | grep -i "www-authenticate")
  #         REALM=$(echo "$AUTH_HEADER" | grep -oP 'realm="\K[^"]+')
  #         SERVICE=$(echo "$AUTH_HEADER" | grep -oP 'service="\K[^"]+')

  #         SCOPE="repository:$NAMESPACE/$IMAGE:pull"
  #         TOKEN=$(curl -sS -u "个人云数据:${{ secrets.ACR_PASSWORD }}" \
  #           "${REALM}?service=${SERVICE}&scope=${SCOPE}" | jq -r '.token // .access_token')

  #         TAGS_JSON=$(curl -sS -H "Authorization: Bearer $TOKEN" \
  #           "https://$REGISTRY/v2/$NAMESPACE/$IMAGE/tags/list")

  #         echo "$TAGS_JSON"

  #         TAG=$(echo "$TAGS_JSON" | jq -r '.tags | sort_by(. | split("_")[0] | tonumber) | last')

  #         if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
  #           echo "failed to get tag"
  #           exit 1
  #         fi

  #         echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
  #         echo "tag=$TAG"

  # deploy:
  #   name: Deploy
  #   needs: check_image_tag
  #   env:
  #     TAG: ${{ needs.check_image_tag.outputs.image_tag }}
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Ansible
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y ansible
      
  #     - name: Setup SSH
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa

  #         cat >> ~/.ssh/config <<EOF
  #         Host dev-server
  #           HostName ${{ secrets.SERVER_HOST }}
  #           User ${{ secrets.SERVER_USER }}
  #           IdentityFile ~/.ssh/id_rsa
  #           StrictHostKeyChecking no
  #         EOF

  #     - name: Setup inventory
  #       run: |
  #         cat > ansible/inventory.ini <<EOF
  #         [dev]
  #         dev-server
  #         EOF

  #     - name: Deploy with Ansible
  #       env:
  #         REGISTRY: ${{ env.REGISTRY }}
  #         NAMESPACE: ${{ env.NAMESPACE }}
  #         IMAGE: ${{ env.IMAGE }}
  #         TAG: ${{ needs.check_image_tag.outputs.image_tag }}
  #         ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  #       run: |
  #         ansible-playbook \
  #           -i ansible/inventory.ini \
  #           ansible/dev/deploy.yml

  deploy:
    name: Deploy
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deploy-ansible repo
        uses: actions/checkout@v4
        with:
          repository: s1line1/ansible-playbook
          path: ansible-playbook
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy with Ansible
        run: |
          cd ansible-playbook && \
          ansible-playbook -i github-actions-demo/inventory.ini github-actions-demo/deploy.yml \
          -e "env=dev acr_password=${{ secrets.ACR_PASSWORD }}" --private-key ~/.ssh/id_rsa -u root
