name: Shift Left
run-name: >-
  ${{ github.event_name == 'pull_request' && format('PR #{0} {1} by {2}', github.event.number, github.event.pull_request.title, github.actor) }}


on:
  pull_request:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-shanghai
  REGISTRY: crpi-notabmu0yl0rr8sv.cn-shanghai.personal.cr.aliyuncs.com
  NAMESPACE: s1line1-test
  IMAGE: github-actions-demo
  # TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  unit_test:
    name: Run Unit Test
    # if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build test image
        run: |
          docker build \
            -f Dockerfile.test \
            -t springboot-test:${{ github.sha }} \
            .

      - name: Run mvn clean verify
        run: |
          docker run --rm \
            springboot-test:${{ github.sha }} \
            bash cicd/run-test.sh

  calculate:
    name: Calculate Tag
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.calculate-tag.outputs.tag }}
    steps:
      - name: Calculate tag
        id: calculate-tag
        run: |
          TAG=$(echo -n '${{ github.sha }}' | sha256sum | cut -d' ' -f1 | head -c 8)
          echo "TAG=${{ github.event.number }}_$TAG" >> "$GITHUB_OUTPUT"
          echo "${{ github.event.number }}_$TAG" > image_tag.txt
      
      - name: echo tag
        run: |
          echo "build image with tag: ${{ steps.calculate-tag.outputs.tag }}"

      - name: Upload tag
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image_tag.txt

  build:
    name: Build image and push
    needs: calculate
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      # 1.1 Login to ACR
      - name: Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
              -u 个人云数据 \
              --password-stdin \
              crpi-notabmu0yl0rr8sv.cn-shanghai.personal.cr.aliyuncs.com

      # 1.2 Checkout
      - uses: actions/checkout@v4

      # 1.3 Build and push image to ACR
      - name: Build and push image to ACR
        run: |
          docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:${{ needs.calculate.outputs.image_tag }}" .
          docker push "$REGISTRY/$NAMESPACE/$IMAGE:${{ needs.calculate.outputs.image_tag }}"

  scan:
    name: Scan image in ACR
    needs: [unit_test, calculate, build]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      # 1.4 Scan image in ACR
      - name: Scan image in ACR
        uses: aliyun/acr-scan@v1
        with:
          region-id: "${{ env.REGION_ID }}"
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
          repository: "${{ env.NAMESPACE }}/${{ env.IMAGE }}"
          tag: ${{ needs.calculate.outputs.image_tag }}