name: CI:Test Actions Workflows
run-name: >-
  ${{ github.event_name == 'pull_request' && format('PR CI Test Actions Workflows') }}

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  test:
    name: Run shift-left and Deploy Workflows
    uses: s1line1/actions-workflows/.github/workflows/shift-left.yml@feature_fix_workflows
    with:
      acr-name: "test-acr-name"
      run-number: ${{ github.event.number }}
