name: CI:Test Actions Workflows
run-name: >-
  ${{ github.event_name == 'pull_request' && format('PR CI Test Actions Workflows') }}

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  CICD:
    name: Run shift-left and Deploy Workflows
    uses: s1line1/actions-workflows/.github/workflows/shift-left.yml@feature_fix_workflows
    with:
      acr-name: "github-actions-demo"
      run-number: ${{ github.event.number }}
      tag-sha: ${{ github.sha }}
      region: cn-shanghai
      OSS_ENDPOINT: oss-cn-shanghai.aliyuncs.com
      OSS_BUCKET: bucket-secret
    secrets:
      access_key_id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
      access_key_secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

  test-docker-images:
    needs: CICD
    if: needs.CICD.outputs.has-docker-image == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test-docker-images ${{ needs.CICD.outputs.has-docker-image }}"
          