name: CI:Test Actions Workflows
run-name: >-
  ${{ github.event_name == 'pull_request' && format('PR CI Test Actions Workflows') }}

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  test:
    name: Test Actions Workflows
    # runs-on: ubuntu-latest
    # steps:
    #   - name: test Actions Workflows
    #     run: |
    #       echo "Testing Actions Workflows..."
    uses: s1line1/actions-workflows/.github/workflows/shift-left.yml@feature_fix_workflows
    with:
      acr-name: "test-acr-name"

