name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build test image
        run: |
          docker build \
            -f Dockerfile.test \
            -t springboot-test:${{ github.sha }} \
            .

      - name: Run mvn clean verify
        run: |
          docker run --rm \
            springboot-test:${{ github.sha }} \
            bash cicd/run-test.sh